# Generated by Django 3.2.5 on 2021-09-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20210928_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='logo',
            field=models.ImageField(default='defaultskilllogo.png', null=True, upload_to=''),
        ),
    ]
